version: '3.9'

services:

  apifinciclo:
    container_name: afinfinciclo
    image: martin.azurecr.io/apifinciclo:latest
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 5000:8910
    env_file:
      - ./.env
